---
title: "Introduction"
output: ioslides_presentation
---

## Goals for semester

- Analyze and interpret general(ized) linear models

- Be able to graph your data

- Identify and diagnose problems when they arise

##Important links
- [Class website](https://josh-jackson.github.io/Psych5067/)

- [Class readings](https://josh-jackson.github.io/Psych5067/readings.html)

- [LSR](https://health.adelaide.edu.au/psychology/ccs/teaching/lsr/)

- [Example data from class (and Rmd and all other materials)](https://github.com/josh-jackson/Psych5067) if you dont want to use class webpage. 

## Important information

- Most important information is on the slides

- Readings serve to supplement and enhance

- Important equations will be presented via slides

## two types of people

- This class is going too slow vs going too fast

- If too fast: ASK QUESTIONS AND COME AND VISIT ME. Also spend lots of time outside of class, learning takes time.

- If too slow: ASK QUESTIONS AND COME AND VISIT ME. There are lots of interesting extensions. I have readings. 

##Goals for today
- Review of last semester
- Overview of this semester

## What should you already know? 

## pragmatics

- R, RStudio 
- Rmarkdown/LaTeX
- Reproducible reports: Rmd/LaTeX -> html/pdf 

- Keep organized: R Projects 
- Keep it visual: ggplot
- Keeping track/sharing: osf, github (recommended)
- Keep it simple and readable: dplyr & tidyverse (strongly recommended)
- Keep it interesting: shiny apps (recommended for advanced users)

## visualizing data

- histograms, probability mass function

- density plot, probability density function, cumulative density function

- bar, box, violin... 1. Avoid wow graphs, 2. use interpretable scales, 3. label 4. always provide a dispersion estimate and 5. if possible include raw data and/or the distribution (as dispersion only can hide oddities)


## Theoretical probability distributions 

- how you measure your variables determine your analytic tool options

- Data generating process defines appropriate analyses 

- binomial, poisson, negative binomial, normal (Gaussian), t, F, chi-square...


## many distributions

- population distribution -> sample distribution -> sampling distrinbution

- standard error is the standard deviation of the sampling distribution

## p-values, NHST and standard opperating procedures 

- p(D|Ho), not p(Ho|D) 

- Type 1 & 2 errors, power, family wise error

- Issues with NHST

- Questionable research practices (QRPs)

## effect size and CIs
- There is imprecision in all that you do

- Common effect size metrics?

- Interpretation and utility of CI? 

- How does the CI relate to the sample and sampling distribution? 

- meta-analytic thinking

## How to suceed (in class)

- Go through slides, work through code
- Apply concepts to your own work
- Devote time

## Last thoughts
- Any questions? 

- Looking forward: This semeter's themes are Relationships and Models





