---
title: "Untitled"
author: "Josh Jackson"
date: "4/26/2017"
output: html_document
---
```{r}
library(tidyverse)
mlm_data <- read.csv("~/Box Sync/5067 Regression Spring/regression/data/mlm_data.csv") 


```


```{r}
# create
# mlm_data <- read.csv("~/Box Sync/5067 Regression Spring/regression/data/mlm_data_full.csv")
#  mlm_data %>%
#   select(PIB_ID, Neuro_Dx, contains("DigSpn_Btotal")) %>%
#   mutate(DigSpn_Btotal_0  = na_if(DigSpn_Btotal_0, 9999.0)) %>%
#   separate(PIB_ID, c('omit', 'ID' ), sep="-") %>%
#   select(-omit) %>%
#   write.csv(file = "mlm_data.csv")

mlm_data_long <- mlm_data %>%
  select(-negT1, - negT2, -negT3, -negT4) %>% 
  gather(time, PA, 2:5) %>%  
  separate(time, c('omit', 'wave' ), sep="T") %>% 
  select(-omit) 

mlm_data_long$wave <- as.numeric(mlm_data_long$wave)
mlm_data_long$gender <- as.factor(mlm_data_long$gender)
mlm_data_long$group <- as.factor(mlm_data_long$group)

cor(mlm_data, use = "pairwise.complete.obs")
?cor
library(psych)
describe(mlm_data$posT1)
```


```{r}
library(lme4)
library(reghelper)
model.1 <- lmer(PA ~ 1 + ( 1 | ID), data = mlm_data_long)
summary(model.1)
ICC(model.1)
```

```{r}
model.2 <- lmer(PA ~ wave + ( 1 | ID), data = mlm_data_long)
summary(model.2)
```

```{r}
model.3 <- lmer(PA ~ wave + ( wave | ID), data = mlm_data_long)
summary(model.3)
```

```{r}
model.4 <- lmer(PA ~ wave*gender + ( wave | ID), data = mlm_data_long)
summary(model.4)
anova(model.4)
```

