---
title: "Interactions take home"
output: html_document
---
# Due: 3/23  
<br>
Turn in via email to: Takehom.krrrtmtti39wm685@u.box.com by attaching an rmd or a rnw file of your code and answers. Use your last name to label the file and include your name as part of the document front/top-matter.  

<br>
All take home projects are **INDEPENDENT** projects; do not share code or answers.   

Using the dataset labeled th.project.4 answer the questions below. The dataset looks at  happiness in college as a relationship with school success, friendship quality, SES, and an intervention group (1= control, 2 = study skills training, 3 = social skills training). (Note that the variable names have spaces in them, which may make it tricky to work with. I suggest renaming the variables)

1. Run a two-predictor regression predicting happiness by friendship and school success  and the interaction between the two. Describe your hypothesis for the interaction using the study variables. Describe in words what exactly the b1, b2 and b3 coefficients are telling us in this model. 

2. What is the mean and SD of your Y, X1, X2, and interaction variables that you used in your regression model?

3. Compute 3 simple regression equations: The regression of Y on X at the mean of X2, at one standard deviation above the mean of X2 (X2hi) and at one standard deviation below the mean of X2 (X2low). Your choice of moderating variable depends on your hypothesis. Write (type) out and interpret each of these simple slope equations. 

4. Graph the three simple slopes within a single plot.

5. Are any of these simple slopes significantly different from 0?

6. How much variance is explained by the interaction?

7. Now run the interaction again, but instead of using the raw/unstandardized metric, use standardized variables. Compute simple slopes. Describe the differences between the standardized and unstandardized models. 

8.  Imagine you concerned at all with non-linear effects masquerading as an interaction? Test this concern. 

9. Run a new regression model, this time with the group variable interacting with friendship. Interpret each of the coefficients in this model and provide a graph of the results.

10. What are the estimated values for each of the groups in #9 controlling for friendship? 

11. Use a different coding scheme than the one you chose to use in #9. How did this change the results? Interpret each of the regression coefficients. 

**** note that the below questions will not be tesed on Exam : 

6. Check each of the six assumptions discussed in class. Note: not every assumption may be directly examined. Describe how you *would* test the assumption. 

7.	Examine possible outliers. Directly state what each plot tells you. Are there any cases that are suspicious?  What is the impact on the analysis of these cases, if any? 
