---
title: "takehome-3"
output: html_document
---

# Due: 2/20  
<br>
Turn in via email to: Takehom.krrrtmtti39wm685@u.box.com by attaching an rmd or a rnw file of your code and answers. Use your last name to label the file (e.g,. "Jackson_takehome3")and include your name as part of the document front/top-matter.  
<br>
All take home projects are **INDEPENDENT** projects; do not share code or answers.   

Please use the th.project.3 dataset to answer the questions below. These data were from a study where physical health was predicted by a happyness measure, socioeconomic status, number of close friends, and a 16 week mood intervention where here was a waitlist control group (coded 0), a positive self affirmation intervention group (1) and a mediation group (2). 

1. Calculate the semi-partial and a partial correlation for health and friends, controlling for SES and happiness using a series of multiple regression analyses (ie do not use a function for semi-partial and partial correlations). 

2. Perform a multiple regression where Health is regressed on friends, SES and happiness. Interpret each coefficient. 

3. Graph the (2-d) relationship between health and happy as found in the above regression. Make sure the association controls for the remaining variables in the model. 

4. For the above regression, calculate variance explained using the anova table and interpret the residual standard error 

5. Include the group variable mood.group into the regression model from #2. 
  a) Interpret the new coefficients
  b) Is there a significant increase in variance explained compared to the initial regression in #2? If so, what is the estimate? 
  c) Recode the group coefficients to -1,0 and 1. Rerun the model. Interpret each regression coefficient including the intercept. 
  d) For the model you ran in c, is the change in variance explained different from the change in variance explained from question b? Why or why not? 


**** note that the below questions will not be tesed on Exam 1: 

6. Check each of the six assumptions discussed in class. Note: not every assumption may be directly examined. Describe how you *would* test the assumption. 

7.	Examine possible outliers. Directly state what each plot tells you. Are there any cases that are suspicious?  What is the impact on the analysis of these cases, if any? 

  
  
  